### ISSUE TITLE
Move SoapySDR.jl here?

### ISSUE THREAD

**Issue by Keno** [JuliaTelecom/Collaboration#2]
Hi @RGerzaguet @ma-laforge @ledoune, I and @staticfloat are doing a bunch of SDR work. We've started with a revival of a SoapySDR wrapper at https://github.com/Keno/SoapySDR.jl. Are you interested in having that live here? Happy to just put it in a new org also, but I figured, we might as well keep the SDR packages all in one place.

**Comment by ma-laforge** [comment]
I am certainly ok with this. Seems like the right home for for SoapySDR to me.

@RGerzaguet : If you are ok with it, I'll add @staticfloat & @Keno as members. Or just add them yourself since you've done it before.

**Comment by RGerzaguet** [comment]
Hello @Keno and @staticfloat, and welcome onboard ! I am very happy to see initiative on SDR and Julia altogether  and as @ma-laforge stated, this organization seems to be the right place.

**Comment by Keno** [comment]
SoapySDR.jl has been transferred, so I'm gonna close this. Can we add @sjkelly to the org also - he'll be working with us on this? Looks like I don't have permissions to do that.

**Comment by RGerzaguet** [comment]
Thanks @Keno 
I have invited @sjkelly and you have now the right to do this in the future :) 

@+R

**Comment by sjkelly** [comment]
Thanks @RGerzaguet, it is much appreciated!
